### ISSUE TITLE
It is possible to move out of the gameplay area

### ISSUE THREAD

**Issue by Achie72** [pmarkee/void-conquerors#1]
**Sys Info:**
OS: Kubutu 16.04
Browser: 74.0.3729.169

**Issue:**
Moving to the right you can 'escape' the black gameplay area. 

**Expected:**
I guess not being able to do that.

**How to replicate:**
Start the game, and press Right Arrow.

**Possible solution:**
Pretty sure this is not intentional, and should have a check around here: https://github.com/pmarkee/void-conquerors/blob/master/Player.gd#L16
Although i'm not familiar with godot really much, i think i should be doable pretty easy. Also i could not replicate this to the left, i may be because the whole screen ends there.

**Comment by pmarkee** [comment]
Thanks for the report, I am actually aware of this issue. I'm not sure what could be wrong since the the player is supposed to be restricted to the game area (https://github.com/pmarkee/void-conquerors/blob/master/Player.gd#L33), I'll look into it.

**Comment by pmarkee** [comment]
@Achie72 this should be fixed now. The player can still move halfway out of the game area, I will fix that too after I added my own sprites to the game instead of the googled images that are currently used (I would need to know exact pixel values and such). Thanks again for the report.
